export const DETAIL_CARD_1_DEFAULT = {
  id: 1,
  mainTitle: "이것은 예시, 다스베이더의 포스는 영원하리!",
  subTitle: "전 은하계를 장악하려는 사스의 음모가 모든 문명을 뒤덮고 있는 것을 막기 위해, 포스의 힘을 빌려 다스베이더와 싸우기 위해 콜로니 행성으로 갔다. 광선검이 부러질지라도!",
  contribution: 60,
  platform: "유튜브",
  roleDescription: "스승님이신 콰이곤 님을 보필하여, 사스의 심복을 처단하는 데에 일조하였다.",
  roles: ["following", "planning", "production", "management", "etc"],
  tools: ["notion", "midjourney", "powerpoint", "premiere"],
  periodStartYear: 2026,
  periodStartMonth: 4,
  periodStartDay: 15,
  periodEndYear: 2026,
  periodEndMonth: 4,
  periodEndDay: 23,
  mainImage: "/images/0/1/9.png",
  subImages: ["/images/0/1/10.png", "/images/0/1/11.png"] as (string | null)[],
  mainImageCaption: "",
  subImageCaptions: ["", ""],
  metrics: ["조회수", "240,000 회", "외부 인용수", "7 회", "댓글 수", "340 개"],
  report: "예시. 사스의 심복을 우주 정거장에서 처단하는 데에 성공하였다. 그러나 그 과정에서 콰이곤 님이 포스의 영면에 접어들었으며, 삐리봉 행성의 시민들이 폭동을 일으켰다.",
  insight: "예시. 콰이곤 님의 패배는 예상하지 못했었다. 전력의 객관적 평가가 가장 중요하고, 이를 위해 적을 사전에 분석해야 한다는 것을 다시금 깨달았다. 그러나 사스의 심복들은 오랫동안 그 정체를 숨기고 있기에, 사전에 적들의 전력을 분석하기 곤란한 면이 있다. 이에 포스의 희망을 새로운 신예 아나킨에게 건다. 아나킨. 너는 선택받은 자라는 것을 명심해라!",
  links: [
    "https://www.youtube.com/watch?v=4wWw1xL8nm8",
    "https://www.youtube.com/watch?v=bpGA7eU8b-M",
    "",
  ],
};

export const EMPTY_DETAIL_CARD = {
  mainTitle: "",
  subTitle: "",
  contribution: 0,
  platform: "",
  roleDescription: "",
  roles: [] as string[],
  tools: [] as string[],
  periodStartYear: null as number | null,
  periodStartMonth: null as number | null,
  periodStartDay: null as number | null,
  periodEndYear: null as number | null,
  periodEndMonth: null as number | null,
  periodEndDay: null as number | null,
  mainImage: null as string | null,
  subImages: [null, null] as (string | null)[],
  mainImageCaption: "",
  subImageCaptions: ["", ""],
  metrics: ["", "", "", "", "", ""],
  report: "",
  insight: "",
  links: ["", "", ""],
};

export const createInitialDetailCardsWithDefault = () => [
  { ...DETAIL_CARD_1_DEFAULT },
  ...Array.from({ length: 9 }, (_, i) => ({ id: i + 2, ...EMPTY_DETAIL_CARD })),
];
