export const OUTPUT_CARD_1_DEFAULT = {
  id: 1,
  mainTitle: "이것은 예시, 그대를 찬란하게 빛나게 할 예시",
  subTitle: "루비콘 강을 건너는 과정을 통해, 무너져가는 로마 제국을 다시 재건하였다. 도탄과 피폐에 빠진 로마 시민들을 위해 굳게 다짐하고, 루비콘 강을 건넜다.",
  contribution: 90,
  platform: "유튜브",
  roleDescription: "루비콘 강을 건너는 과정에서 다리를 교량하고, 수로를 틀어 물의 흐름을 확보했다.",
  roles: ["following", "support", "execution", "analysis", "etc"],
  tools: ["notion", "midjourney", "powerpoint", "premiere"],
  periodStartYear: 2026,
  periodStartMonth: 4,
  periodStartDay: 15,
  periodEndYear: 2026,
  periodEndMonth: 4,
  periodEndDay: 23,
  mainImage: "/images/0/1/6.png",
  subImages: ["/images/0/1/7.png", "/images/0/1/8.png"] as (string | null)[],
  mainImageCaption: "",
  subImageCaptions: ["", ""],
  metrics: ["조회수", "240,000 회", "외부 인용수", "7 회", "댓글 수", "340 개"],
  report: "예시. 성공적인 루비콘 강 도하를 거쳐, 26년 3월 40일, 로마에 들어왔다. 시민들의 반응이 예상과 달랐고, 약 40일 간 외부 주둔하며 원로원과 교섭하고 재입성하였다.",
  insight: "예시. 시민들의 반응은 생각보다 매서웠다. 우리가 주적으로 삼은 크라수스의 통치는 온화하였기에, 이를 진압한 우리 군단에 대한 눈초리가 매서웠다. 직접 확인하기 전까지 말 뿐인 떠들석한 의원과 귀족들의 편지를 믿었던 것이 패착이었다. 이 경험을 통해, 직접 확인하기 전까지 제 3자의 말에 휘둘리지 않아야 한다는 것을 다시 한번 확고히 깨달았다.",
  links: [
    "https://www.youtube.com/watch?v=u6vSX5l8f4Y",
    "https://www.youtube.com/watch?v=1LVp4tvl5O4",
    "",
  ],
};

export const EMPTY_OUTPUT_CARD = {
  mainTitle: "",
  subTitle: "",
  contribution: 0,
  platform: "",
  roleDescription: "",
  roles: [] as string[],
  tools: [] as string[],
  periodStartYear: null as number | null,
  periodStartMonth: null as number | null,
  periodStartDay: null as number | null,
  periodEndYear: null as number | null,
  periodEndMonth: null as number | null,
  periodEndDay: null as number | null,
  mainImage: null as string | null,
  subImages: [null, null] as (string | null)[],
  mainImageCaption: "",
  subImageCaptions: ["", ""],
  metrics: ["", "", "", "", "", ""],
  report: "",
  insight: "",
  links: ["", "", ""],
};

export const createInitialOutputCardsWithDefault = () => [
  { ...OUTPUT_CARD_1_DEFAULT },
  { id: 2, ...EMPTY_OUTPUT_CARD },
  { id: 3, ...EMPTY_OUTPUT_CARD },
  { id: 4, ...EMPTY_OUTPUT_CARD },
  { id: 5, ...EMPTY_OUTPUT_CARD },
];
